# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 082525222ebc56034bb2309384a437e5685aabdf85e455173cc90d3f20b9bf3e9a19df0dbd79884af8d780c6c634df7fe16631e26af9ae3066fb1909a3dc1944

test:
  secret_key_base: c3f448ab3bce6a384b3b62e9b41157fab103a0e5e4d70ca6c107ebcdd404e7bb6ce9e21a40105628f51d5d22aa3c88f44ad7566a18c19776f1afcc36df678597

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
